### ISSUE TITLE
Can not install with "pip3 install -U ckiptagger[tf,gdown]"

### ISSUE THREAD

**Issue by heather-lau** [ckiplab/ckiptagger#11]
I tried to install with "ckiptagger[tf,gdown]", but it returns "no matches found: ckiptagger[tf,gdown]", but when I just install "ckiptagger" without buckets, it works fine, please help.

**Comment by jacobvsdanniel** [comment]
Are you using Python 3.7, which TensorFlow currently does not support?

**Comment by heather-lau** [comment]
> Are you using Python 3.7, which TensorFlow currently does not support?

Sorry, it's my problem, I'm using zsh, I should type this:
`pip3 install -U ckiptagger \[tf,gdown \]`

thanks

**Comment by wastu01** [comment]
@heather-lau 
I encountered the same issue on my Mac using zsh. Thanks for this solution, it helped! I had to use: `pip install -U ckiptagger\[tf,gdown\]` as well.
