### ISSUE TITLE
Any roadmap for releasing training code?

### ISSUE THREAD

**Issue by sih4sing5hong5** [ckiplab/ckiptagger#13]
We want to train model for Hakka and Taioanoe. Will CKIP release the training code?
Or any suggestion?

**Comment by jacobvsdanniel** [comment]
Original data processing and training scripts will be prepared for ad hoc private licenses of the package. Unfortunately, their open source release is currently not guaranteed.

For now, try to wrap your own training loop with
- Model.compute_loss_for_a_batch() https://github.com/ckiplab/ckiptagger/blob/b2a3237d9b766a4dbcb27003ba6468fcaba3bb57/src/model_ws.py#L369-L374
- Model.predict_label_for_a_batch()
https://github.com/ckiplab/ckiptagger/blob/b2a3237d9b766a4dbcb27003ba6468fcaba3bb57/src/model_ws.py#L399-L404

**Comment by sih4sing5hong5** [comment]
Thank you, we will try.
