### ISSUE TITLE
Add support for tensorflow v2 or above?

### ISSUE THREAD

**Issue by hms5232** [ckiplab/ckiptagger#28]
您好：最近在嘗試使用這個套件，在分析文本階段會不斷出現下列錯誤：
`AttributeError: 'WS' object has no attribute 'model'` 
及
`AttributeError: module 'tensorflow' has no attribute 'variable_scope'`
等等的錯誤。
在查詢後發現我使用的 tensorflow 版本為 2.3.0 ，和 README 中提及的版本需求不符（貌似 2 以上都會有這個問題，參考 https://github.com/ckiplab/ckiptagger/issues/17#issuecomment-546679627 ），因此決定降版。但在過程中發現最低只能降到 2.2.0，才發現原來是 Python 3.8 不支援 tensorflow 2.2 之前的版本（[ref](https://www.tensorflow.org/install/pip?hl=zh-tw)）。雖然降板可能可以解決此問題，但還是希望日後或許能增加對新版 tensorflow 的支援（或期望 Python 3.8 能用舊版的 tensorflow 了）

**Comment by p208p2002** [comment]
@hms5232 
你好, 我最近也有遇到同樣的問題然後有改了一個tf2的相容版本,可以參考一下
https://github.com/p208p2002/ckiptagger

**Comment by hms5232** [comment]
> 
> 
> @hms5232
> 你好, 我最近也有遇到同樣的問題然後有改了一個tf2的相容版本,可以參考一下
> https://github.com/p208p2002/ckiptagger

感謝提供方法，有空的時候我再來試試
目前是先安裝 Python 3.7 版在我的 Ubuntu 20.04 上解決這個問題

**Comment by jacobvsdanniel** [comment]
Merged with #27。目前版本和TensorFlow 1.15及2.3皆相容。

**Comment by hms5232** [comment]
非常感謝！實際測試在下面環境下可以成功運作！

- Python==3.8
- ckiptagger==0.2.1
- ensorflow==2.3.0

另外 README 中關於環境需求的部份可能也要記得更新一下囉
