### ISSUE TITLE
python 版本可能需要建議在 3.6 以上

### ISSUE THREAD

**Issue by sudoghut** [ckiplab/ckiptagger#3]
感謝貴項目的開源以及開放模型下載！非常好用！

用 python 3.5 run `from ckiptagger import data_utils, construct_dictionary, WS, POS, NER` 的時候會提示 f-string 錯誤：

![image](https://user-images.githubusercontent.com/8538710/64260116-e2c4cd00-cf5c-11e9-82a1-26768f06d0f2.png)

將 python 版本升級到 >=3.6 即可解決。

可能需要在 Requirements 裡面只建議用戶使用 python >= 3.6 版本。

**Comment by jacobvsdanniel** [comment]
目前先提高需求至python>=3.6

**Comment by PichuChen** [comment]
Translating: 
Thank you for your open source and model downloads! very useful!

When using python 3.5 run `from ckiptagger import data_utils, construct_dictionary, WS, POS, NER` you will be prompted with f-string error:
=> image

Upgrade the python >=3.6 to fix it.

It may be necessary to only recommend users to use python >= 3.6 in Requirements.
