### ISSUE TITLE
CC license not for software and source code

### ISSUE THREAD

**Issue by ryanho** [ckiplab/ckiptagger#4]
FAQ from [CC website](https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software):

> Unlike software-specific licenses, CC licenses do not contain specific terms about the distribution of source code, which is often important to ensuring the free reuse and modifiability of software. Many software licenses also address patent rights, which are important to software but may not be applicable to other copyrightable works. Additionally, our licenses are currently not compatible with the major software licenses, so it would be difficult to integrate CC-licensed work with other free software. Existing software licenses were designed specifically for use with software and offer a similar set of rights to the Creative Commons licenses.

You should consider another license that  design for software.

**Comment by jacobvsdanniel** [comment]
Instead of, say, messing with BSD by adding a (to me) trouble-making non-commercial clause, I'll see if I could push this towards an open but viral license like GPL. For the time being, CC NC seems the most readily available license.

**Comment by ckipma** [comment]
We changed the license to GPL 3.0.
