### ISSUE TITLE
請問利用自定義字典影響斷詞結果，為什麼不會影響實體辨識結果呢？

### ISSUE THREAD

**Issue by tynnie** [ckiplab/ckiptagger#43]
在斷詞過程中，可加上自定義字典影響斷詞結果
例如以下列方式斷詞：
```
text = '即起至4月14日在官邸進行居家隔離，暫停所有公開行程；其後再進行7天的自主健康管理。'
ws_list = ws([text], coerce_dictionary=construct_dictionary({'7天的自主健康管理': 2}))
pos_list = pos(ws_list)
```
可得理想斷詞結果如下
```
即(D)　起(Ng)　至(Caa)　4月(Nd)　14日(Nd)　在(P)　官邸(Nc)　進行(VC)　居家(Na)　隔離(VC)　，(COMMACATEGORY)　暫停(VHC)　所有(Neqa)　公開(VHC)　行程(Na)　；(SEMICOLONCATEGORY)　其後(Ncd)　再(D)　進行(VC)　7天的自主健康管理(Na)　。(PERIODCATEGORY)
```
但以此斷詞結果進行實體辨識
```
entity_list = ner(ws_list, pos_list)
```
實體辨識結果卻未參考加上自定義字典的斷詞結果，而呈現以下結果：
```
[('7天', 'DATE', (32, 34)), ('4月14日', 'DATE', (3, 8))]
```

請問為什麼加上自定義字典的斷詞結果，無法影響實體辨識結果呢？
我的理解是斷詞結果中成功斷出「7天的自主健康管理」，實體辨識過程應以「7天的自主健康管理」進行實體辨識，而非仍以未參考自定義字典所會斷出的「7天」進行實體辨識，因此提出此問題，希望您可以撥空回應，謝謝！

**Comment by jacobvsdanniel** [comment]
Duplicated; see also: https://github.com/ckiplab/ckiptagger/issues/21#issuecomment-606515488
實體辨識模型確會參考斷詞結果，但辨識結果不一定按照斷詞邊界，如此可以得到盡量精確的實體辨識結果。
例如 ('7天', 'DATE', (32, 34)) 實為正確的實體辨識結果，使用者可依需求再決定是否採用，例如可以自行剔除和斷詞結果不同的實體。

**Comment by tynnie** [comment]
瞭解，謝謝！
