### ISSUE TITLE
AttributeError: 'NER' object has no attribute 'model'

### ISSUE THREAD

**Issue by xijiz** [ckiplab/ckiptagger#8]
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    ner = NER("./data")
  File "/home/xijiz/.local/lib/python3.6/site-packages/ckiptagger/api.py", line 241, in __init__
    config.w_token_to_vector, config.w_embedding_d = _load_embedding(os.path.join(data_dir, "embedding_word"))
  File "/home/xijiz/.local/lib/python3.6/site-packages/ckiptagger/api.py", line 328, in _load_embedding
    vector_list = np.load(vector_file)
  File "/home/xijiz/.local/lib/python3.6/site-packages/numpy/lib/npyio.py", line 453, in load
    pickle_kwargs=pickle_kwargs)
  File "/home/xijiz/.local/lib/python3.6/site-packages/numpy/lib/format.py", line 738, in read_array
    array = numpy.fromfile(fp, dtype=dtype, count=count)
numpy.core._exceptions.MemoryError: Unable to allocate array with shape (406737300,) and data type float32
Exception ignored in: <bound method NER.__del__ of <ckiptagger.api.NER object at 0x7fb03ba2f358>>
Traceback (most recent call last):
  File "/home/xijiz/.local/lib/python3.6/site-packages/ckiptagger/api.py", line 258, in __del__
    self.model.sess.close()

**Comment by xijiz** [comment]
I totally follow the example code without modification, but it failed to load NER model.

**Comment by jacobvsdanniel** [comment]
"numpy.core._exceptions.MemoryError: Unable to allocate array with shape (406737300,) and data type float32"
At first glance, the root cause seems to be the system refusing to allocate a large array.

**Comment by xijiz** [comment]
My test code is here.

`
from ckiptagger import data_utils, construct_dictionary, WS, POS, NER


ws = WS("./data")
pos = POS("./data")
ner = NER("./data")

sentence_list = [
    "傅達仁今將執行安樂死，卻突然爆出自己20年前遭緯來體育台封殺，他不懂自己哪裡得罪到電視台。",
    "美國參議院針對今天總統布什所提名的勞工部長趙小蘭展開認可聽證會，預料她將會很順利通過參議院支持，成為該國有史以來第一位的華裔女性內閣成員。",
    "",
    "土地公有政策?？還是土地婆有政策。.",
    "… 你確定嗎… 不要再騙了……",
    "最多容納59,000個人,或5.9萬人,再多就不行了.這是環評的結論.",
    "科長說:1,坪數對人數為1:3。2,可以再增加。",
]

word_sentence_list = ws(
    sentence_list,
    # sentence_segmentation=True, # To consider delimiters
    # segment_delimiter_set = {",", "。", ":", "?", "!", ";"}), # This is the defualt set of delimiters
    # recommend_dictionary = dictionary1, # words in this dictionary are encouraged
    # coerce_dictionary = dictionary2, # words in this dictionary are forced
)

pos_sentence_list = pos(word_sentence_list)

entity_sentence_list = ner(word_sentence_list, pos_sentence_list)

`

**Comment by xijiz** [comment]
> "numpy.core._exceptions.MemoryError: Unable to allocate array with shape (406737300,) and data type float32"
> At first glance, the root cause seems to be the system refusing to allocate a large array.

Oh, I see. Thank you!

**Comment by xijiz** [comment]
The reason is that my laptop has limited memory, and the system refuses to allocate an array. I have solved this problem. Thank you again!
